name: github-actions-test
on:
  push:
    branches-ignore:
      - main
      - homolog
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - uses: actions/checkout@v3

      - name: generated keys
        run: php artisan key:generate

      - name: install depends
        run: composer install

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: run laravel tests
        run: php artisan test
