name: github-actions-test
on:
  push:
    branches-ignore:
      - main
      - homolog
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1

      - uses: actions/checkout@v3

      - name: install depends
        run: composer install

      - name: run laravel tests
        run: php artisan test
